project:
  type: website

website:
  title: "Mathias Louboutin"
  image: mathias.png
  google-analytics: "G-ERCRWL13YZ"
  search: true

  page-footer:
    center:
      - text: "2023 Copyright (c) Mathias Louboutin"
    right:
      - icon: twitter
        href: https://twitter.com/Louboutjunior
        aria-label: Twitter
      - icon: github
        href: https://github.com/mloubout
        aria-label: GitHub
      - icon: envelope-at-fill
        href: mailto:mathias.louboutin@gmail.com

  navbar:
    logo: mathias.png
    collapse-below: lg
    background: light

    tools:
      - icon: github
        menu:
          - text: Personal
            href: https://github.com/mloubout
          - text: Sponsor
            href: https://github.com/sponsors/mloubout
          - text: SLIM@gatech
            url: https://github.com/slimgroup
      - icon: twitter
        href: https://twitter.com/Louboutjunior
      - icon: linkedin
        href: https://www.linkedin.com/in/mathias-louboutin-a116b957/
      - icon: envelope-at-fill
        href: mailto:mathias.louboutin@gmail.com

    right:
      - href: https://scholar.google.com/citations?user=RGVC664AAAAJ&hl=en
        icon: Google_Scholar_logo.svg

    left:
      - href: index.qmd
        text: Home
      - href: pubs/publications.qmd
        text: Publications
      - href: software.qmd
        text: Software
      - href: resume.qmd
        text: Resume

  sidebar:
    - id: pubs
      title: "Publications"
      style: "floating"
      collapse-level: 1
      contents:
        - href: pubs/publications.qmd
          text: Introduction
        - title: Thesis
          href: pubs/Thesis.qmd
        - title: Journal Papers
          href: pubs/Journals.qmd
        - title: Conferences
          href: pubs/Conferences.qmd
        - title: Presentations
          href: pubs/Presentations.qmd
        - title: Technical Reports
          href: pubs/TechReports.qmd
        - title: Unpublished
          href: pubs/Unpublished.qmd

    - id: soft
      title: Resume
      contents:
        - href: resume.qmnd

    - id: cv
      title: Software
      contents:
        - href: Software.qmnd

format:
  html:
    theme:
      light: spacelab
      dark: cyborg
    css: styles.css
    toc: true
    link-external-newwindow: True
    code-copy: true

execute:
  freeze: auto


