project:
  type: website

website:
  title: "Mathias Louboutin"
  image: images/banner.png
  google-analytics: "G-ERCRWL13YZ"
  repo-url: https://github.com/mloubout/mloubout.github.io
  repo-actions: [issue]
  search: true
  page-navigation: true
  reader-mode: true

  twitter-card: 
    site: "@Louboutjunior"

  page-footer:
    center:
      - text: "2023 Copyright (c) Mathias Louboutin"
    right:
      - icon: twitter
        href: https://twitter.com/Louboutjunior
        aria-label: Twitter
      - icon: github
        href: https://github.com/mloubout
        aria-label: GitHub
      - icon: envelope-at-fill
        href: mailto:mathias.louboutin@gmail.com
      - icon: globe
        href: https://www.devitocodes.com/
  
  navbar:
    logo: images/devito-logo.svg
    collapse-below: lg
    background: light

    tools:
      - icon: github
        menu:
          - text: Personal
            href: https://github.com/mloubout
          - text: Sponsor
            href: https://github.com/sponsors/mloubout
          - text: SLIM@gatech
            url: https://github.com/slimgroup
      - icon: twitter
        href: https://twitter.com/Louboutjunior
      - icon: linkedin
        href: https://www.linkedin.com/in/mathias-louboutin-a116b957/
      - icon: envelope-at-fill
        menu:
          - text: Personal
            href: mailto:mathias.louboutin@gmail.com
          - text: Professional
            href: mailto:mathias@devitocodes.com
      - icon: slack
        href: https://join.slack.com/t/devitocodes/shared_invite/zt-gtd2yxj9-Y31YKk_7lr9AwfXeL2iMFg
      - icon: globe
        href: https://www.devitocodes.com/

    left:
      - href: index.qmd
        text: Home
      - href: content/pubs/publications.qmd
        text: Publications
      - href: content/software/software.qmd
        text: Software
      - href: content/resume.qmd
        text: Resume

  sidebar:
    - id: pubs
      title: "Publications"
      style: "floating"
      collapse-level: 1
      contents:
        - href: content/pubs/publications.qmd
          text: Introduction
        - title: Journal Papers
          href: content/pubs/Journals.qmd
        - title: Conferences
          href: content/pubs/Conferences.qmd
        - title: Presentations
          href: content/pubs/Presentations.qmd
        - title: Technical Reports
          href: content/pubs/TechReports.qmd
        - title: Unpublished
          href: content/pubs/Unpublished.qmd

    - id: soft
      title: "Software"
      contents:
        - content/software/software.qmd
    
    - id: resume
      title: Resume
      contents:
        - href: content/resume.qmd

format:
  html:
    theme:
      light: spacelab
      dark: cyborg
    css: assets/styles.css
    toc: true
    link-external-newwindow: True
    code-copy: true
    code-fold: true

execute:
  freeze: auto


