project:
  type: website

website:
  title: "Mathias Louboutin"
  image: images/banner.png
  google-analytics: "G-ERCRWL13YZ"
  repo-url: https://github.com/mloubout/mloubout.github.io
  repo-actions: [issue]
  search: true
  page-navigation: true
  reader-mode: true

  twitter-card: 
    site: "@Louboutjunior"

  page-footer:
    center:
      - text: "© Mathias Louboutin 2023–2026"
    right:
      - icon: twitter
        href: https://twitter.com/Louboutjunior
        aria-label: Twitter
      - icon: github
        href: https://github.com/mloubout
        aria-label: GitHub
      - icon: envelope-at-fill
        href: mailto:mathias.louboutin@gmail.com
      - icon: globe
        href: https://www.devitocodes.com/

  navbar:
    logo: images/devito-logo.svg
    collapse-below: lg
    background: light

    tools:
      - icon: github
        menu:
          - text: Personal
            href: https://github.com/mloubout
          - text: Sponsor
            href: https://github.com/sponsors/mloubout
          - text: SLIM@gatech
            url: https://github.com/slimgroup
      - icon: twitter
        href: https://twitter.com/Louboutjunior
      - icon: linkedin
        href: https://www.linkedin.com/in/mathias-louboutin-a116b957/
      - icon: envelope-at-fill
        menu:
          - text: Personal
            href: mailto:mathias.louboutin@gmail.com
          - text: Professional
            href: mailto:mathias@devitocodes.com
      - icon: slack
        href: https://join.slack.com/t/devitocodes/shared_invite/zt-2hgp6891e-jQDcepOWPQwxL5JJegYKSA
      - icon: globe
        href: https://www.devitocodes.com/

    left:
      - href: index.qmd
        text: Home
      - text: Publications
        menu:
          - href: content/pubs/publications.qmd
            text: Overview
          - href: content/pubs/Journals.qmd
            text: Journal articles
          - href: content/pubs/Conferences.qmd
            text: Conference papers
          - href: content/pubs/Presentations.qmd
            text: Presentations
          - href: content/pubs/TechReports.qmd
            text: Technical reports
          - href: content/pubs/Scholar.qmd
            text: Google Scholar
      - href: content/software/software.qmd
        text: Software
      - href: content/resume.qmd
        text: Resume
      - text: Tutorials
        menu:
          - href: content/tutorials/tutorials.qmd
            text: Overview
          - href: content/tutorials/devitoapi/00_sympy.ipynb
            text: Devito API
          - href: content/tutorials/devitotutos/01_modelling.ipynb
            text: Modeling and imaging
          - href: content/tutorials/judituto/01_intro.ipynb
            text: JUDI workflows

  sidebar:
    - id: tuto
      style: "docked"
      title: "Tutorials"
      collapse-level: 0
      contents:
        - section: "Tutorials"
          href: content/tutorials/tutorials.qmd
          contents:
            - section: "Devito API"
              contents: content/tutorials/devitoapi/*.ipynb
            - section: "Devito tutorials"
              contents: content/tutorials/devitotutos/*.ipynb
            - section: "JUDI tutorials"
              contents: content/tutorials/judituto/*.ipynb

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: assets/styles.css
    toc: true
    link-external-newwindow: True
    code-copy: true
    code-fold: false
    execute: 
      enabled: false


execute:
  freeze: auto
