---
title: "Presentations"
bibliography: presentations.bib
callout-icon: false
nocite: |
  @*
---

## Improved seismic monitoring of CO2 sequestration with the weighted joint recovery model

@yin2021ML4SEISMICism  [Link](https://slim.gatech.edu/Publications/Public/Conferences/ML4SEISMIC/2021/yin2021ML4SEISMICism/Tue-11-20-Yin.html)

::: {.callout-note collapse="true"}
# Abstract

Time-lapse seismic monitoring of CO2 sequestration is challenging because the time-lapse signature of CO2 plumes is weak in amplitude and often contaminated by imaging artifacts due to coarsely sampled, noisy, and non-replicated surveys. In this talk, we present a sparsity-promoting least-squares imaging method where the baseline, and the current and past monitor surveys are inverted jointly. We demonstrate that the sensitivity of seismic monitoring can be improved by inverting for the common component { \textemdash } i.e., the component shared by all vintages, and innovations with respect to this common component. Combining this joint approach with weighted l1, 2-norm minimization leads to a monitoring scheme capable of detecting irregular CO2-plume growth in a realistic geological setting.
:::

## Regularizing waveform inversion by projections onto intersections of convex sets

@peters2015SINBADFrwi  [Link](https://slim.gatech.edu/Publications/Public/Conferences/SINBAD/2015/Fall/peters2015SINBADFrwi/peters2015SINBADFrwi.pdf)

::: {.callout-note collapse="true"}
# Abstract

Common strategies to regularize waveform inversion (and other geophysical inverse problems) are adding quadratic penalty terms to the objective function or filtering the gradients used to update the model estimate. An example are penalties or filters to prevent/filter spurious high spatial frequency oscillations in the model while working with low frequency data. We present an alternative way of regularization, which works by projecting the model onto an intersection of convex sets, where each sets encodes certain desired model properties. This approach has certain theoretical and practical advantages over quadratic penalties or gradient filters. Some examples of useful convex sets in various challenging waveform inversion settings are shown on both real and synthetic data.
:::

## Uncertainty-aware time-lapse CO$_2$ monitoring with learned end-to-end inversion

@yin2022ML4SEISMICutc  [Link](https://slim.gatech.edu/Publications/Public/Conferences/ML4SEISMIC/2022/yin2022ML4SEISMICutc/index.html)

::: {.callout-note collapse="true"}
# Abstract

Seismic monitoring of CO2 sequestration is computationally expensive as it involves modeling of both fluid-flow physics modeling and wave physics and differentiation through the solvers with respect to the subsurface properties of interest. In this talk, we demonstrate the effectiveness of learned coupled inversion framework using a pre-trained Fourier neural operator as a learned surrogate for the fluid-flow simulator, which greatly reduces the cost associated with fluid-flow modeling and differentiation through the solver. We study the effectiveness and correctness of inversion based on Fourier neural operator surrogate and a normalizing flow prior. We also demonstrate the efficacy of this framework on monitoring the growth of CO2 plumes during sequestration, and on uncertainty quantification of the permeability and CO2 plumes with conditional normalizing flow. With this framework, we can further forecast the CO2 plume in the future without any acquired seismic data with uncertainty estimation.
:::

## Randomized linear algebra for inversion

@louboutin2021ML4SEISMICrla  [Link](https://slim.gatech.edu/Publications/Public/Conferences/ML4SEISMIC/2021/louboutin2021ML4SEISMICrla/Tue-10-20-Louboutin.pdf)

::: {.callout-note collapse="true"}
# Abstract

Inverse problems in exploration geophysics or machine learning heavily relies on linear algebra and large matrices manipulations. To tackle the growing cost of storing these matrices, randomized algorithms have been developed to obtain information from these matrices via randomized sketching. Inspired by previous work on extended image volumes, we will first show in this talk how the seismic imaging condition can be expressed in a randomized linear algebra framework leading to drastic memory savings. In a second part, we will extend this idea to convolutional neural networks to reduce the memory cost of training by orders of magnitude. We will demonstrate the practicality of these methods on representative examples.
:::

## Domain-specific abstractions for large-scale geophysical inverse problems

@witte2019HOTCSEdsagip  [Link](https://slim.gatech.edu/Publications/Public/Lectures/HotCSE/2019/witte2019HOTCSEdsagip/witte2019HOTCSEdsagip.pdf)

::: {.callout-note collapse="true"}
# Abstract

During these times of sustained low oil prices, it is essential to look for new innovative ways to collect (time-lapse) seismic data at reduced costs and preferably also at reduced environmental impact. By now, there is an increasing body of corroborating evidence { \textemdash } whether these are simulated case studies or actual acquisitions on land and marine { \textemdash } that seismic acquisition based on the principles of compressive sensing delivers on this premise by removing the need to acquire replicated dense surveys. Up to ten-fold increases in acquisition efficiency have been reported by industry while there are indications that this breakthrough is only the beginning of a paradigm shift where full-azimuth time-lapse processing will become a reality. To familiarize the audience with this new technology, I will first describe the basics of compressive sensing, how it relates to missing-trace interpolation and simultaneous source acquisition, followed by how this technology is driving innovations in full-azimuth (time-lapse) acquisition, yielding high-fidelity data with a high degree of repeatability and at a fraction of the costs.
:::

## Multifidelity conditional normalizing flows for physics-guided Bayesian inference

@siahkoohi2021ML4SEISMICmcn  [Link](https://slim.gatech.edu/Publications/Public/Conferences/ML4SEISMIC/2021/siahkoohi2021ML4SEISMICmcn/Mon-11-45-Siahkoohi.pdf)

::: {.callout-note collapse="true"}
# Abstract

We introduce a scalable Bayesian inference approach that combines techniques from deep learning with a physic-based variational inference formulation. Bayesian inference for ill-posed inverse problems is challenged by the high-dimensionality of the unknown, computationally expensive forward operator, and choosing a prior distribution that accurately encodes prior knowledge on the unknown. To handle this situation and to assess uncertainty, we propose to approximate the posterior distribution using a pretrained conditional normalizing flow, which is trained on existing low- and high-fidelity estimations of the unknown. To further improve the accuracy of this approximation, we use transfer learning and finetune this normalizing flow by minimizing the Kullback-Leibler divergence between the predicted and the desired high-fidelity posterior density. This amounts to minimizing a physic-based variational inference objective with respect to the network weights, which we believe might scale better than Bayesian inference with Markov Chain sampling methods. We apply the proposed Bayesian inference approach to seismic imaging where we use quasi-real data obtained from the Parihaka dataset.
:::

## Adjoint operators as summary functions in amortized Bayesian inference frameworks

@orozco2022ML4SEISMICaos  [Link](https://slim.gatech.edu/Publications/Public/Conferences/ML4SEISMIC/2022/orozco2022ML4SEISMICaos/index.html)

::: {.callout-note collapse="true"}
# Abstract

An important concern in seismic inverse problems is the large and varying size of observed data. The large size can cause computational cost concerns and its varying size (such as when changing receiver geometries) implies the need to rerun inference algorithms from scratch for each new observation. Motivated by these two problems, we take inspiration from the statistics literature which commonly relies on summary statistic of observed data. Summary statistic compress the observed data leaving only information needed for inference. In this work, we argue that the adjoint operator provides a natural candidate for a summary function in the context of physics-based inverse problems. We first mathematically show that for certain general assumptions transforming data under the adjoint operator defines a new conditional distribution which preserves the expectations of the original posterior. We validate our hypothesis by evaluating our framework in a learned amortized inference algorithm. Our seismic and medical synthetic experiments show computational gains and increased quality of point estimates using our framework. We discuss statistical metrics that show our learned posterior is well calibrated therefore justifying its use in uncertainty quantification.
:::

## Noise robust and time-domain formulations of Wavefield Reconstruction Inversion

@wang2017SINBADFnra  [Link](https://slim.gatech.edu/Publications/Public/Conferences/SINBAD/2017/Fall/wang2017SINBADFnra/wang2017SINBADFnra.pdf)

::: {.callout-note collapse="true"}
# Abstract

We propose a wave-equation-based subsurface inversion method that in many cases is more robust than conventional Full-Waveform Inversion. The new formulation is written in a denoising form that allows the synthetic data to match the observed ones up to a small error. Compared to regular Full-Waveform Inversion, our method treats the noise arising from the data meassuring/recording process and that from the synthetic modelling process separately. Compared to Wavefields Reconstruction Inversion, the new formulation mitigates the difficulty of choosing the penalty parameter λ. To solve the proposed optimization problem, we develop an efficient frequency domain algorithm that alternatively updates the model and the data. Numerical experiments confirm strong stability of the proposed method by comparisons between the results of our algorithm with that from both plain FWI and a weighted formulation of the FWI. We also discuss a new memory efficient time-domain formulation for Wavefield Reconstruction Inversion based on duality.
:::

## A large-scale framework in Julia for fast prototyping of seismic inversion algorithms

@witte2017SINBADFals  [Link](https://slim.gatech.edu/Publications/Public/Conferences/SINBAD/2017/Fall/witte2017SINBADFals/witte2017SINBADFals.pdf)

::: {.callout-note collapse="true"}
# Abstract

We present our progress on a large-scale seismic modeling workflow in Julia for wave-equation based inversion. The software offers a range of high-level abstractions to easily express PDE constrained optimization problems in terms of linear algebra expressions, while utilizing the DSL Devito to symbolically express the underlying PDEs and to generate fast and parallel code for solving them. Data containers and linear operators can be set up without much effort from input SEG-Y data and scale to large-scale 3D applications. This talk provides an overview of the basic functionalities of our software and applications to least squares imaging and 3D FWI.
:::

## Extending the search space of time-domain adjoint-state FWI w/ randomized implicit time shifts

@louboutin2015SINBADFess  [Link](https://slim.gatech.edu/Publications/Public/Conferences/SINBAD/2015/Fall/louboutin2015SINBADFess/louboutin2015SINBADFess.pdf)

::: {.callout-note collapse="true"}
# Abstract

We introduce a modified adjoint-state method for time domain FWI that allows us to extend the research space. As a result, we arrive at a formulation where the sensitivity to cycle skipping is reduced. Our method obtains results with the same computational costs as FWI (The PDE solved is the same) but with significantly reduced memory costs. We use new results in non-convex optimization to justify the method as well as new regularization techniques and stochastic optimization to improve the behavior of the algorithm.
:::

## Time-lapse seismic survey design by maximizing the spectral gap

@zhang2022ML4SEISMICtss  [Link](https://slim.gatech.edu/Publications/Public/Conferences/ML4SEISMIC/2022/zhang2022ML4SEISMICtss/index.html)

::: {.callout-note collapse="true"}
# Abstract

While time-lapse seismic has been applied successfully to CO2 sequestration monitoring, it remains a challenging problem since replicated dense surveys come at a very high cost in the field. Wavefield reconstruction based on matrix completion (MC) from randomized subsampled data is an efficient way to reduce operational costs. This technique allows for accurate time-lapse reconstruction by employing the joint recovery model (JRM), which capitalizes on the fact that different vintages share a common component. However, combining JRM with optimal time-lapse acquisition survey design remains an unexplored area of research. In expander graph theory, spectral gap (SG) reveals the source-receiver layout connectivity and is related to reconstruction quality during MC. Building on these insights, we proposed a simulation free time-lapse survey design based on JRM that aims to get similar reconstructed quality without insisting on replicate surveys, which significantly reduces the cost in the field. This approach uses the simulated annealing algorithm to find subsampling masks for each vintage. Numerical experiments confirm a direct correlation between increased spectral gap and promising time-lapse reconstruction quality.
:::

## A dual formulation of wavefield reconstruction inversion for large-scale seismic inversion

@rizzuti2021ML4SEISMICdfw  [Link](https://slim.gatech.edu/Publications/Public/Conferences/ML4SEISMIC/2021/rizzuti2021ML4SEISMICdfw/Tue-10-55-Rizzuti.pdf)

::: {.callout-note collapse="true"}
# Abstract

Many of the seismic inversion techniques currently proposed that focus on robustness with respect to the background model choice are not apt to large-scale 3D applications, and the methods that are computationally feasible for industrial problems, such as full waveform inversion, are notoriously limited by convergence stagnation and require adequate starting models. We propose a novel solution that is both scalable and less sensitive to starting models or inaccurate parameters (such as anisotropy) that are typically kept fixed during inversion. It is based on a dual reformulation of the classical wavefield reconstruction inversion, whose empirical robustness with respect to these issues is well documented in the literature. While the classical version is not suited to 3D, as it leverages expensive frequency-domain solvers for the wave equation, our proposal allows the deployment of state-of-the-art time-domain finite-difference methods, and is potentially mature for industrial-scale problems.
:::

## High-performance seismic applications of OPESCI

@louboutin2016SINBADFhps  [Link](https://slim.gatech.edu/Publications/Public/Conferences/SINBAD/2016/Fall/louboutin2016SINBADFhps/louboutin2016SINBADFhps.pdf)

::: {.callout-note collapse="true"}
# Abstract

We present our latest geophysical applications built on OPESCI. By using a high-level symbolic API, we allow for fast development and easy implementation of various (acoustic, VT, TTI) wave propagators relevant to exploration geophysics. We start by highlighting possibilities in an acoustic setting including classical operators such as forward modelling and linearised forward (Born) modelling as well as more advanced operators deriving from wave equations with double dipoles and the application of the PDE to a wavefield instead of applying its inverse. We will also show that the performance (time to solution) of this code is on par with industrial software libraries (10\% faster on the full SEAM model). We finally present our implementation of 3D TTI modelling and its adjoint including out comprehensive testing framework. This is joint work with Gerard Gorman
:::

## ML4Seismic open-source software: updates and developments

@louboutin2022ML4SEISMICmos  [Link](https://slim.gatech.edu/Publications/Public/Conferences/ML4SEISMIC/2022/louboutin2022ML4SEISMICmos/index.html)

::: {.callout-note collapse="true"}
# Abstract

Software is at the core of research and development in inverse problems. At SLIM, we have experience developing scalable and performant software, such as our legacy parallel MATLAB framework. With ML4Seismic, we are dedicated to build on this experience to develop HPC open source software (OSS) for the scientific community in collaboration with our partners. In this talk, we will describe our OSS Julia and Python environment, our high-level abstraction principles, and the range of solutions we offer for seismic processing and inversion and for machine learning. We will emphasize our aim to provide scalable software that can be easily applied to industrial problems.
:::

## Data driven Gradient Sampling for seismic inversion

@louboutin2017SINBADFddg  [Link](https://slim.gatech.edu/Publications/Public/Conferences/SINBAD/2017/Fall/louboutin2017SINBADFddg/louboutin2017SINBADFddg.pdf)

::: {.callout-note collapse="true"}
# Abstract

We present in this work an extension of the Gradient Sampling algorithm presented at the last EAGE in Paris. We previously showed the potential of this algorithm playing with implicit time-shifts to represent the wavefield of a slightly perturbed velocity model. We introduce an extension where the weights of the Gradient Sampling algorithm are obtained with the solve of data-based quadratic subproblem instead of at random. The update direction is the a more accurate representation of the true Gradient Sampling update direction.
:::

## Learned extensions for wave-based simulation and inversion

@louboutin2022ML4SEISMIClew  [Link](https://slim.gatech.edu/Publications/Public/Conferences/ML4SEISMIC/2022/louboutin2022ML4SEISMIClew/index.html)

::: {.callout-note collapse="true"}
# Abstract

We introduce a new method that explores velocities as an operator (extended velocities) for wave-equation based inversion. Through this extended formulation, we obtain the known benefits of working with subsurface offset volumes. The offset-dependence of these volumes has been studied in the linear case, i.e as part of extended Born scattering and extended least-squares reverse-time migration, but has been avoided for non-linear inversion due to computational concderns and challenges. By using techniques from randomized linear algebra, we will show that we can work with extended velocities for inversion while maintaining an acceptable computational cost much lower than solving one PDE per extended velocity model.
:::

## Effective scaling of numerical surrogates via domain-decomposed Fourier neural operators

@grady2022ML4SEISMICesn  [Link](https://slim.gatech.edu/Publications/Public/Conferences/ML4SEISMIC/2022/grady2022ML4SEISMICesn/index.html)

::: {.callout-note collapse="true"}
# Abstract

Numerical surrogates are models which learn to mimic a complex physical process (such as the solution to a PDE produced by a solver) from a set of input/output pairs. Fourier neural operators (FNOs) are a specific type of numerical surrogate which use a learned matched filter to quickly approximate solutions to relatively smooth complex physical processes. In the case of carbon capture sequestration (CCS) technology, FNOs have been shown to well-approximate solutions to the two-phase flow equations, with speedups of 1, 000 to 10, 000 times at inference time versus a tradtitional solver. This speed combined with the fact that FNOs are differentiable with respect to their input parameters allows for inverse and uncertainty quantification problems to theoretically be solved on real 3D data, a previously intractible task. However, due to the size of the input data, network weights, and optimizer state, FNOs have thus far been limited to small to medium 2D and 3D problems, well below the size of an industry standard such as the Sleipner benchmark. Here we alleviate this problem by proposing a model-parallel FNO which makes use of domain decomposition of the input data and network weights, and exploits architectural features of FNOs to also include a natural form of asynchronous pipeline parallelism. Our network can scale to arbitrary problem sizes on CPU and GPU systems.
:::

## Normalizing flows for regularization of 3D seismic inverse problems

@orozco2022ML4SEISMICnfr  [Link](https://slim.gatech.edu/Publications/Public/Conferences/ML4SEISMIC/2022/orozco2022ML4SEISMICnfr/index.html)

::: {.callout-note collapse="true"}
# Abstract

We present the first known exploration of a normalizing flow (NF) for generative 3D volumes. First, we tackle computational issues surrounding the high dimensionality of our desired 3D volume output. This is of particular concern in normalizing flows since their invertibility constraint implies equal dimension of output and input. Our findings show that by " freezing " expensive layers we can efficiently train a normalizing flow on 3D volumes. Using this NF architecture, we train a generative model on volume sections of the 3D BG compass model. Our method produces visually plausible generative samples which are efficient to produce. We demonstrate its practical use by using our trained generative model as an implicit prior in a Maximum A Posteriori (MAP) framework. We evaluate this MAP framework by estimating the solution of a inverse problem in seismic imaging. Our method results in higher SNR estimates than the baseline and in less iterations, importantly saving the computational cost of evaluating the expensive 3D PDE solver during optimization. Finally, through scaling analysis of training cost, we show that NF convolutional layers allow this approach to scale favorably to larger volumes.
:::

## Latest developments in Devito

@louboutin2017SINBADFldi  [Link](https://slim.gatech.edu/Publications/Public/Conferences/SINBAD/2017/Fall/louboutin2017SINBADFldi/louboutin2017SINBADFldi.pdf)

::: {.callout-note collapse="true"}
# Abstract

We present an overview of the latest developments in Devito. We introduced Devito in the previous meeting as a prototype finite-difference DSL for seismic modelling and inversion. We are presenting here the latest improvements and functionalities of Devito. We will also discuss the current future plans as well as non-supported features that the audience may be interested in. This presentation will be followed by/mixed with a hands-in tutorial if the time and resources allows it.
:::

## Amortized velocity continuation with Fourier neural operators

@yin2022ML4SEISMICavc  [Link](https://slim.gatech.edu/Publications/Public/Conferences/ML4SEISMIC/2022/yin2022ML4SEISMICavc/index.html)

::: {.callout-note collapse="true"}
# Abstract

Velocity continuation aims to map the migration image using one background model to the image using another background model. It is of great importance to quantify the uncertainty in seismic imaging result from various background models. With Fourier neural operators as a learned surrogate, this continuation from a given background model to an unseen background model can be quite accurately estimated with near-zero cost. However, the limitation of the prior art is that the input background model and the survey area are assumed to be fixed. The main contribution of this work is to extend the Fourier neural operator surrogate to be amortized over different given background models and survey areas. We verify the effectiveness of our learned surrogates by a realistic example on different areas of Parihaka dataset against different background models.
:::

## ML4Seismic open source software environment

@louboutin2021ML4SEISMICmos  [Link](https://slim.gatech.edu/Publications/Public/Conferences/ML4SEISMIC/2021/louboutin2021ML4SEISMICmos/Mon-10-10-Louboutin.pdf)

::: {.callout-note collapse="true"}
# Abstract

Software is at the core of research and development in inverse problems. At SLIM, we have experience developing scalable and performant software, such as our legacy parallel MATLAB framework. With ML4Seismic, we are dedicated to build on this experience to develop HPC open source software (OSS) for the scientific community in collaboration with our partners. In this talk, we will describe our OSS Julia and Python environment, our high-level abstraction principles, and the range of solutions we offer for seismic processing and inversion and for machine learning. We will emphasize our aim to provide scalable software that can be easily applied to industrial problems.
:::

## Simulation-based framework for geological carbon storage monitoring

@yin2022ML4SEISMICsfg  [Link](https://slim.gatech.edu/Publications/Public/Conferences/ML4SEISMIC/2022/yin2022ML4SEISMICsfg/index.html)

::: {.callout-note collapse="true"}
# Abstract

While various monitoring modalities exist to track the behavior of CO2 plumes to ensure safe operations and compliance with regulatory requirements, active 3D time-lapse seismic monitoring has proven superior but costly. At SLIM, we aim to reduce the operating costs by optimizing acquisition design, to help drive innovations in seismic monitoring acquisition design and imaging, and to test novel time-lapse acquisition and imaging technologies in silico at scale. In this talk, we will introduce our open-source software platform simulation-based monitoring design framework. We demonstrate how to make use of proxy models for seismic properties derived from real 3D imaged seismic and well data to conduct realistic synthetic geological carbon storage projects. Furthermore, we discuss our proposed sparse non-replicated seismic acquisition and cutting-edge methodology to recover the dense data or to directly image the sparse non-replicated via joint recovery model. This automatic workflow ends with deep neural classifiers to detect potential CO2 leakage over seal through pressure-induced fault openings. We envisage the development of an automatic workflow to handle the large number of continuously monitored CO2 injection sites needed to help combat climate change.
:::

## De-risking GCS projects with explainable CO$_2$ leakage detection in time-lapse seismic images

@erdinc2022ML4SEISMICdgp  [Link](https://slim.gatech.edu/Publications/Public/Conferences/ML4SEISMIC/2022/erdinc2022ML4SEISMICdgp/index.html)

::: {.callout-note collapse="true"}
# Abstract

With the global deployment of Carbon, capture and storage (CCS) technology to combat climate change, there is an associated risk of contamination with CO2 leaking back to the atmosphere. Thus, it requires continuous monitoring of CO2 after the injection stops at the storage site. In this work, we generated synthetic CO2 plume development data with both leakage and no leakage scenarios. We trained a convolutional neural network (CNN) discriminative classifier and also a generative classifier and compared their performances in CO2 leakage detection. The accuracy of our discriminative classifier on the test data is 85\% and that of the generative classifier is 90\%. The Class Activation Mapping (CAM) results of the discriminative classifier and the latent space representation of our dataset in the case of generative classifier strengthens our claims about trustworthy leakage classification.
:::

## Open Performance portablE SeismiC Imaging { \textendash } -OPESCI

@gorman2016SINBADFopp  [Link](https://slim.gatech.edu/Publications/Public/Conferences/SINBAD/2016/Fall/gorman2016SINBADFopp/gorman2016SINBADFopp.pdf)

::: {.callout-note collapse="true"}
# Abstract

In this project, we introduce OPESCI-FD, a Python package built on symbolic mathematics to automatically generate Finite Difference models from a high-level description of the model equations. We investigate applying this framework to generate the propagator program used in seismic imaging. We implement the 3D acoustic and anisotropic FD scheme as an example and demonstrate the advantages of usability, flexibility and accuracy of the framework. The design of OPESCI-FD aims to allow rapid development, analysis and optimisation of Finite Difference programs. OPESCI-FD is the foundation for continuing development by the OPESCI project team, building on the research presented in this report. This talk concludes by reviewing the further developments that are already under way, as well as the scope for extension to cater for other equations and numerical schemes. This joint work with SINBAD and SENAI CIMATEC and has received additional funding from Intel.
:::

## Scaling SINBAD software to 3-D on Yemoja

@dasilva2015SINBADFsss  [Link](https://slim.gatech.edu/Publications/Public/Conferences/SINBAD/2015/Fall/dasilva2015SINBADFsss/dasilva2015SINBADFsss.pdf)

::: {.callout-note collapse="true"}
# Abstract

We present early results on the scalability of SINBAD ' s wavefield reconstruction and wave-equation based inversion technologies on Yemoja, a 17k core cluster made available to us by BG Group at SENAI CIMATEC Supercomputing Centre in Brazil.
:::

## Julia for Geoscience

@yin2022TRANSFORMjulia  [Link](https://transform.softwareunderground.org/2022-julia-for-geoscience)

::: {.callout-note collapse="true"}
# Abstract

In this tutorial, we will introduce the Julia programming language to the geoscience community, covering topics such as I/O, data processing, inversion, and machine learning. We will begin by installing Julia and relevant packages. Through a series of tutorials, we will demonstrate Julia ' s abstraction power and show how to load and plot data, write your own functions/operators, form and solve a geophysical inverse problem, and demonstrate how to integrate wave-equation solvers in Julia with machine learning frameworks. The intent of this presentation is to provide an introductory level tutorial that will be useful to members of the geoscience community.
:::

