on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1'
          arch: x64

      - name: Make latest publication pages
        run: |
          julia -e 'using Pkg;Pkg.add("BibTeX")'
          julia scripts/mkpubs.jl
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
